name: own_dog
description: A new Flutter project.
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.6
  firebase_analytics: ^5.0.14
  firebase_crashlytics: ^0.1.3+3
  image_picker: ^0.6.7

  tflite: ^1.0.6
  flare_flutter: ^2.0.3
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/pic.png
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/flares/Doggo-storyoggo.flr

  fonts:
    - family: Mitr
      fonts:
        - asset: fonts/Mitr-Regular.ttf

    - family: K2D
      fonts:
        - asset: fonts/K2D-Regular.ttf
